name: CROUS Alert

on:

  schedule:

    - cron: "*/15 * * * *"

  workflow_dispatch:


jobs:

  check:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install Python
      uses: actions/setup-python@v5

      with:
        python-version: "3.12"


    - name: Install dependencies

      run: |

        pip install requests beautifulsoup4


    - name: Run checker

      env:

        TELEGRAM_TOKEN:
          ${{ secrets.TELEGRAM_TOKEN }}

        TELEGRAM_CHAT_ID:
          ${{ secrets.TELEGRAM_CHAT_ID }}

      run: |

        python crous_checker.py
